### ISSUE TITLE
When will the pretrained checkpoints be provided?

### ISSUE THREAD

**Issue by YingqingHe** [universome/stylegan-v#10]

**Comment by universome** [comment]
Hi! We currently plan to release the checkpoints closer the official paper release on CVPR (which is June 20). If you need, we can provide our preliminary checkpoint on FaceForensics 256x256:
- [~11k-kimg version](https://disk.yandex.ru/d/OhSRcjsf5LPdgQ)
- [~23k-kimg version](https://disk.yandex.ru/d/pAjelIeqkdzSAg)

**Comment by YingqingHe** [comment]
Thank you!!

**Comment by rliptech** [comment]
Could you also provide the checkpoint for SkyTimelapse? Thank you!

**Comment by universome** [comment]
Hi @rliptech 
Sorry, I have missed your reply.
Here is our SkyTimelapse checkpoint: [https://disk.yandex.ru/d/pAjelIeqkdzSAg](https://disk.yandex.ru/d/pAjelIeqkdzSAg)

**Comment by rliptech** [comment]
Thank you!

**Comment by hse1032** [comment]
Hi @universome,

Sorry for bothering you, but I found the checkpoint of SkyTimelapse you uploaded is actually checkpoint of FaceForensics.
Attached image is sampled from checkpoint: https://disk.yandex.ru/d/pAjelIeqkdzSAg

![000002](https://user-images.githubusercontent.com/115209649/230114523-ce526c1e-1d3a-49c2-a860-d370351971b4.jpg)



Can you provide the checkpoint for SkyTimelapse?

Thanks,

**Comment by universome** [comment]
Hi @hse1032 I am sorry for this and for my so late replies...
I've accidentally named the FFS checkpoint as SkyTimelapse and vice versa. I've renamed them correctly.
Thank you for reporting this issue!
