### ISSUE TITLE
Questions about calc_metrics_for_dataset

### ISSUE THREAD

**Issue by johannwyh** [universome/stylegan-v#11]
I encountered an issue of `calc_metrics_for_dataset.py` that, the `dummy_dataset_cfg` is set as,
```python
dummy_dataset_cfg = OmegaConf.create({'max_num_frames': 10000, 'sampling': {}})
```
while constructing the `VideoFramesFolderDataset`, it computes `raw_shape` by calling
```python
raw_shape = [len(self._video_idx2frames)] + list(self._load_raw_frames(0)[0][0].shape)
``` 
`self._load_raw_frames(0)` has `frame_idx` as None, therefore requires to sample frames
```python
frames_idx = sample_frames(self.sampling_dict, total_video_len=min(total_len, self.max_num_frames)) + offset
```
This `sampling_dict` is an empty dict, as is set in `dummy_dataset_cfg`, and causes an error that `type` key is not found in the dict when `sample_frames` function executes
```python
if cfg['type'] == 'random':
```
Seemingly I should not arbitrarily set a `type` for the sampling_dict as both sampling methods require more arguments in sampling_dict, in which there is nothing available.

May I know how to modify the video dataset construction logic for metric evaluation?

**Comment by johannwyh** [comment]
Currently I modified the way to compute `raw_shape` as 
```python
raw_shape = [len(self._video_idx2frames)] + list(self._load_raw_frames(0, [0])[0][0].shape)
```
giving the `frame_idx` a list `[0]`. Does it make sense?

**Comment by universome** [comment]
Hi, I am sorry that you had to dig into all those details due to my mistake and sorry for replying that late. The above change which you made seems reasonable to me, it shouldn't break anywhere.

**Comment by universome** [comment]
I've just [incorporated](https://github.com/universome/stylegan-v/commit/e2f95809b807c6a5447117950cbe67144f558127) your changes into the repo. If you like, you can alternatively create a PR with them and i will merge it. Thank you a lot of point out to this error, it's a very crucial part of the code. I am trying to understand now how it was working for me before...

**Comment by johannwyh** [comment]
Thanks for your kind reply. Just modify your repo directly as I have fixed this bug and move on with my project. I did no version management locally.

Anyway, your framework for metric calculation is awesome, very easy to use.
