### ISSUE TITLE
How to avoid setting up the environment from environment.yaml

### ISSUE THREAD

**Issue by skymanaditya1** [universome/stylegan-v#12]
Hi, I am trying to setup stylegan-v on a slurm server. However, I am a little constrained by the space where I can install the environment related packages. I see that to reduce the effort of setting up the packages themselves, you provide these nice commands -- 

conda env create -f environment.yaml -p env
conda activate ./env

However, I already have all the pip packages setup in a different environment which I activate when running other repos. I have a custom dataset setup in the format specified in this repository, and the corresponding yaml files modified/created. 

When I try the running the training code -- python src/infra/launch.py hydra.run.dir=. exp_suffix=my_experiment_name env=local dataset=custom_dataset dataset.resolution=256 num_gpus=4

I get the following error -- 

<=== TRAINING COMMAND END ===>
There are uncommited changes. Continue? [y/N]: y
Creating a symlink to /ssd_scratch/cvit/aditya1/baselines/stylegan-v/data, so try not to delete it occasionally!
Created a project dir: /ssd_scratch/cvit/aditya1/baselines/stylegan-v/experiments/how2sign_faces_stylegan-v_random3_max32_how2sign_faces_exp-aaf99e5
Saved training command in /ssd_scratch/cvit/aditya1/baselines/stylegan-v/experiments/how2sign_faces_stylegan-v_random3_max32_how2sign_faces_exp-aaf99e5/training_cmd.sh
Saved config in /ssd_scratch/cvit/aditya1/baselines/stylegan-v/experiments/how2sign_faces_stylegan-v_random3_max32_how2sign_faces_exp-aaf99e5/experiment_config.yaml
sh: 1: /ssd_scratch/cvit/aditya1/baselines/stylegan-v/env/bin/python: not found

This is because I think somehow you are trying to activate the environment "env" which would have been setup if the exact steps as outlined in your repo were followed. How do I run given that I already have a conda environment setup with all the necessary packages installed.

I am however get stylegan_v to train if I follow the steps that sets up the "env" environment.

**Comment by universome** [comment]
Hi! You are using `configs/env/local.yaml` environment config. By default, it [assumes](https://github.com/universome/stylegan-v/blob/master/configs/env/local.yaml#L3) that your python bin is located in
- `python_bin: ${env.project_path}/env/bin/python`

You should change that line to point to the path with your common environment bin.

**Comment by skymanaditya1** [comment]
Thanks a lot! Closing the issue.
