### ISSUE TITLE
SLURM Unrecognized Option

### ISSUE THREAD

**Issue by CodeBlo** [universome/stylegan-v#17]
Hi,

We are trying to use the SLURM to submit the job by setting slurm=true but we are getting an unrecognized option error. 

`sbatch: unrecognized option '--python_bin=~/mc/stylegan-v/env/bin/python'`

With the print only option the full command is:
```
sbatch --constraint=v100 --time=1-0 --gres=gpu:2 --cpus-per-task=5 --mem-per-gpu=32G --cpus-per-gpu=5 --comment=mc_stylegan-v_random3_max32_mc --output ~/mc/stylegan-v/experiments/mc_stylegan-v_random3_max32_mc-None/slurm_0.log  --export=ALL,--project_dir=~/mc/stylegan-v/experiments/mc_stylegan-v_random3_max32_mc-None --python_bin=~/mc/stylegan-v/env/bin/python --python_script=~/mc/stylegan-v/experiments/mc_stylegan-v_random3_max32_mc-None/src/infra/slurm_job.py  src/infra/slurm_job_proxy.sh
```

I think the error comes from the --export=ALL option which does not have commas between the python bin and project dir. How can we fix this?

**Comment by zqh0253** [comment]
Hi, I have also encountered this problem. I manage to solve this by adding a function in `src/infra/utils.py`:
```
def cfg_to_export_args_str(cfg: DictConfig, use_dashes=True) -> str:
    dashes = '--' if use_dashes else ''

    return ','.join([f'{dashes}{p}={cfg[p]}' for p in cfg])
```
and call this function in `configs/infra.yaml` by:
```
env_args_str:
  _target_: src.infra.utils.cfg_to_export_args_str
  cfg: ${env_args}
  use_dashes: false
```
In this case the export options will be seperated by commas.

**Comment by CodeBlo** [comment]
Thanks!!

**Comment by universome** [comment]
Frankly, I didn't expect that anyone will be using my slurm infrastructure :)
