### ISSUE TITLE
Questions about details of hyperparameters in AlignedTimeEncoder

### ISSUE THREAD

**Issue by SongDoHou** [universome/stylegan-v#21]
Hi, thank you for sharing this amazing works!!

Can I ask you about the hyperparameters in AlignedTimeEncoder?

When we train the model on SkyTimelapse dataset,
what is the values of the member variables (time_enc_dim, min_period_len, max_period_len) in AlignedTimeEncoder?

I think each values are 256, 256, 1024. Is it correct?

(Current I'm on limited (HW and Internet) situation, It's hard to run it.)

**Comment by universome** [comment]
Hi, thank you!
Yes, the hyperparameters for SkyTimelapse are the ones which you specified

**Comment by SongDoHou** [comment]
Thank you so much!!

Can I ask you one more??

How to set the parameters value when we inference using "generate.py" for an hour?

**Comment by universome** [comment]
You mean, how to generate an hour-long video using the inference script?
That's tricky to be honest. By default, the video length is controlled by the [`--video_len` argument](https://github.com/universome/stylegan-v/blob/master/src/scripts/generate.py#L36) (and also `--fps` of course, but let's consider it is fixed to 25 frames per second). If you want to generate a video which lasts N seconds, then you need to set `--video_len` to `N * 25`. But generating an hour-long video (i.e. 3600 * 25 = 90000 frames) would take very much time and will likely result in RAM running out of space. So you can generate it in chunks (controlling the start frame index with `--time_offset` argument) and then concatenate the videos with something like `ffmpeg`.

**Comment by SongDoHou** [comment]
Thank you for letting me know.

I appreciate it!!
