### ISSUE TITLE
About FaceForensics Dataset

### ISSUE THREAD

**Issue by Talegqz** [universome/stylegan-v#24]
Thanks for your excellent work！
I am new to this field and I'm curious about how do you extract mask for FaceForensics dataset?
I found the this dataset does not provide mask for youtube video.

**Comment by universome** [comment]
Hi Qingzhe, thank you! FaceForensics *do* provide masks in their dataset (though you might need to download them separately). We then crop the videos with [`src/scripts/preprocess_ffs.py`](https://github.com/universome/stylegan-v/blob/master/src/scripts/preprocess_ffs.py)

**Comment by Talegqz** [comment]
Thanks for your help! I will download all data.
