### ISSUE TITLE
Question about FVD calculation

### ISSUE THREAD

**Issue by hse1032** [universome/stylegan-v#30]
Thanks you for sharing this great codebase!

I have some question about the FVD caculation in this repository.

As noted in paper, you use (train + test) split for UCF-101 dataset and (train) split for other datasets.

Then, when you calculating the real statistics of FVD,
did you also sample real data from (train + test) split for UCF-101 dataset and (train) split for other datasets?

Thanks,

**Comment by universome** [comment]
Hi, @hse1032 ! The real statistics for FVD were computed on the set of images that was used to train the model. For UCF, we used the `train+test` split to compute the real statistics for FVD. For other datasets, we used the `train` split (e.g., we discarded the val/test splits for them if they were available).

**Comment by hse1032** [comment]
Thank you for prompt reply!
