### ISSUE TITLE
Question about the release of Pre-trained checkpoints

### ISSUE THREAD

**Issue by kkakkkka** [universome/stylegan-v#31]
Thank you for your excellent work! I am wondering if you could please inform me when you intend to release the pretrained checkpoints. Your response would be highly appreciated. Thank you very much!

**Comment by universome** [comment]
Hi @kkakkkka , I am awfully sorry for not replying in time. Our checkpoints are located [here](https://disk.yandex.ru/d/v7MS7zu4mmZxXw).

**Comment by kkakkkka** [comment]
Thanks!
