### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by CodeBlo** [universome/stylegan-v#4]
It would be really nice to know what are the minimum system requirements to train a custom dataset. 

Thanks!

**Comment by universome** [comment]
Hi! We trained all the 256x256 models on 4 V100s with 32 GB each for ~2 days.  It is very similar in training time to [StyleGAN2-ADA](https://github.com/NVlabs/stylegan2-ada-pytorch). When training on a custom dataset, please keep in mind that the `model.generator.time_enc.min_period_len` parameter affects the motion quality a lot: for example, we used `model.generator.time_enc.min_period_len=16` for Face Forensics and `model.generator.time_enc.min_period_len=256` for SkyTimelapse. In some sense, it reflects the speed of motion — the smaller it is, the more high-frequency the motions would be

**Comment by CodeBlo** [comment]
Thanks a lot!!!

**Comment by universome** [comment]
Welcome! Feel free to ask any further questions if you'll face any issues.
Oh, I forgot to add that in fact our model does not need 32GB of memory when trained on 4 GPUs.
In fact, it consumes <10GB of memory on each GPU.
