### ISSUE TITLE
FVD Metrics

### ISSUE THREAD

**Issue by leoShen917** [universome/stylegan-v#41]
@universome Hello, I wonder if it is necessary to normalise the data so that it is distributed between [-1,1] when calculating the FVD metrics, I see that there is a normalisation operation in the original repository but I don't find it in your code. 
Looking forward to your reply, thanks!

**Comment by universome** [comment]
Hi! The I3D torchscript model takes a [0, 255] videos in uint8 format and performs all the normalization internally.
